import { readFile, writeFile } from 'node:fs/promises';
const source = await readFile(new URL('./engine.mjs', import.meta.url), 'utf8');
const bundled = `// Generated by build.mjs from engine.mjs.\n(() => {\n${source.replace(/^export /gm, '')}\nglobalThis.__bilingualKoTranslationEngine = TranslationEngine;\n})();\n`;
await writeFile(new URL('./engine-content.js', import.meta.url), bundled);
